server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/LeoVergaraS/microservices-data-project
          search-path: config-data
  application:
    name: config-service